name: Send Random Hadith to Telegram

on:
  schedule:
    - cron: '*/1 * * * *' # setiap 1 menit
  workflow_dispatch:

jobs:
  send_hadith:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: '-1002576241215'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Send random hadith to Telegram
        uses: actions/github-script@v6
        with:
          script: |
            await (async () => {
              const id = Math.floor(Math.random() * 50) + 1;  // ganti 50 sesuai total hadits
              const url = `https://hadis-api-id.vercel.app/hadith/abu-dawud/${id}`;
              const res = await fetch(url);
  
              if (!res.ok) throw new Error('Failed to fetch hadith');
              const data = await res.json();
              const message = `
              ${data.arab}
              
            ${data.id}
              `;
  
              const sendRes = await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_TOKEN}/sendMessage`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                  chat_id: '-1002576241215', // TELEGRAM_CHAT_ID
                  text: message
                }),
              });
  
              if (!sendRes.ok) {
                const errText = await sendRes.text();
                throw new Error('Telegram API error: ' + errText);
              }
  
              console.log(`✅ Hadith terkirim: ID ${id}`);
            })();
