name: Send Random Hadith to Telegram

on:
  schedule:
    - cron: '0 * * * *' # setiap 1 jam
  workflow_dispatch:

jobs:
  send_hadith:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: '-1002557349745'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Send random hadith to Telegram
        uses: actions/github-script@v6
        with:
          script: |
            await (async () => {
              const perawiList = [
                { name: "Abu Dawud", slug: "abu-dawud", total: 4419 },
                { name: "Ahmad", slug: "ahmad", total: 4305 },
                { name: "Bukhari", slug: "bukhari", total: 6638 },
                { name: "Darimi", slug: "darimi", total: 2949 },
                { name: "Ibnu Majah", slug: "ibnu-majah", total: 4285 },
                { name: "Malik", slug: "malik", total: 1587 },
                { name: "Muslim", slug: "muslim", total: 4930 },
                { name: "Nasai", slug: "nasai", total: 5364 },
                { name: "Tirmidzi", slug: "tirmidzi", total: 3625 }
              ];
            
              const randomPerawi = perawiList[Math.floor(Math.random() * perawiList.length)];
              const id = Math.floor(Math.random() * randomPerawi.total) + 1;
              
              const url = `https://hadis-api-id.vercel.app/hadith/${randomPerawi.slug}/${id}`;
              const res = await fetch(url);
  
              if (!res.ok) throw new Error('Failed to fetch hadith');
              const data = await res.json();
              const message = `
              ${data.arab}
              
            ${data.id}

            HR. ${data.name}
              `;
  
              const sendRes = await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_TOKEN}/sendMessage`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                  chat_id: '-1002557349745', // TELEGRAM_CHAT_ID
                  text: message
                }),
              });
  
              if (!sendRes.ok) {
                const errText = await sendRes.text();
                throw new Error('Telegram API error: ' + errText);
              }
  
              console.log(`✅ Hadith terkirim: ID ${id}`);
            })();
